window.DOPPEL_COMPARISONS = [
  {
    "id": "bridge-val-03",
    "dataset": "bridge",
    "split": "val",
    "number": 3,
    "title": "Moving a yellow toy",
    "focus": "Object shape during transport",
    "directory": "assets/comparisons/bridge/val/03",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-04",
    "dataset": "bridge",
    "split": "val",
    "number": 4,
    "title": "Moving a wooden cylinder",
    "focus": "Placement and upright orientation",
    "directory": "assets/comparisons/bridge/val/04",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-05",
    "dataset": "bridge",
    "split": "val",
    "number": 5,
    "title": "Moving a red block off a tower",
    "focus": "Block shape and placement",
    "directory": "assets/comparisons/bridge/val/05",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-06",
    "dataset": "bridge",
    "split": "val",
    "number": 6,
    "title": "Moving a bunch of grapes",
    "focus": "Object placement",
    "directory": "assets/comparisons/bridge/val/06",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-08",
    "dataset": "bridge",
    "split": "val",
    "number": 8,
    "title": "Placing a pot on a cloth",
    "focus": "Pot shape during contact",
    "directory": "assets/comparisons/bridge/val/08",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-11",
    "dataset": "bridge",
    "split": "val",
    "number": 11,
    "title": "Moving a can across the counter",
    "focus": "Object persistence",
    "directory": "assets/comparisons/bridge/val/11",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-12",
    "dataset": "bridge",
    "split": "val",
    "number": 12,
    "title": "Moving a green block",
    "focus": "Block orientation",
    "directory": "assets/comparisons/bridge/val/12",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-14",
    "dataset": "bridge",
    "split": "val",
    "number": 14,
    "title": "Closing a drawer",
    "focus": "Drawer geometry",
    "directory": "assets/comparisons/bridge/val/14",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-18",
    "dataset": "bridge",
    "split": "val",
    "number": 18,
    "title": "Stacking a green block on a yellow block",
    "focus": "Block geometry",
    "directory": "assets/comparisons/bridge/val/18",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-val-20",
    "dataset": "bridge",
    "split": "val",
    "number": 20,
    "title": "Lifting a green cloth",
    "focus": "Cloth deformation",
    "directory": "assets/comparisons/bridge/val/20",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-01",
    "dataset": "bridge",
    "split": "ood",
    "number": 1,
    "title": "Moving a pot between burners",
    "focus": "Object transport and destination",
    "directory": "assets/comparisons/bridge/ood/01",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-03",
    "dataset": "bridge",
    "split": "ood",
    "number": 3,
    "title": "Placing a banana on a burner",
    "focus": "Object identity and placement",
    "directory": "assets/comparisons/bridge/ood/03",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-05",
    "dataset": "bridge",
    "split": "ood",
    "number": 5,
    "title": "Placing a green object in a bowl",
    "focus": "Object placement",
    "directory": "assets/comparisons/bridge/ood/05",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-07",
    "dataset": "bridge",
    "split": "ood",
    "number": 7,
    "title": "Covering a pot with a lid",
    "focus": "Lid placement",
    "directory": "assets/comparisons/bridge/ood/07",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-08",
    "dataset": "bridge",
    "split": "ood",
    "number": 8,
    "title": "Placing a blue spoon",
    "focus": "Utensil motion",
    "directory": "assets/comparisons/bridge/ood/08",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-10",
    "dataset": "bridge",
    "split": "ood",
    "number": 10,
    "title": "Lifting a green fruit",
    "focus": "Object attachment to the gripper",
    "directory": "assets/comparisons/bridge/ood/10",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-16",
    "dataset": "bridge",
    "split": "ood",
    "number": 16,
    "title": "Placing a lid on a pot",
    "focus": "Lid geometry and contact",
    "directory": "assets/comparisons/bridge/ood/16",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-17",
    "dataset": "bridge",
    "split": "ood",
    "number": 17,
    "title": "Moving a lid across the stove",
    "focus": "Lid shape and position",
    "directory": "assets/comparisons/bridge/ood/17",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-19",
    "dataset": "bridge",
    "split": "ood",
    "number": 19,
    "title": "Lifting and placing a metal pot",
    "focus": "Pot shape and transport",
    "directory": "assets/comparisons/bridge/ood/19",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "bridge-ood-20",
    "dataset": "bridge",
    "split": "ood",
    "number": 20,
    "title": "Releasing a blue fork",
    "focus": "Utensil shape at placement",
    "directory": "assets/comparisons/bridge/ood/20",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-01",
    "dataset": "robomind",
    "split": "val",
    "number": 1,
    "title": "Putting a bottle in a bin",
    "focus": "Object transport and persistence",
    "directory": "assets/comparisons/robomind/val/01",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-02",
    "dataset": "robomind",
    "split": "val",
    "number": 2,
    "title": "Picking up a paper ball",
    "focus": "Object pickup",
    "directory": "assets/comparisons/robomind/val/02",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-03",
    "dataset": "robomind",
    "split": "val",
    "number": 3,
    "title": "Opening the upper drawer",
    "focus": "Drawer opening distance",
    "directory": "assets/comparisons/robomind/val/03",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-06",
    "dataset": "robomind",
    "split": "val",
    "number": 6,
    "title": "Pulling open a drawer",
    "focus": "Drawer geometry and motion",
    "directory": "assets/comparisons/robomind/val/06",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-08",
    "dataset": "robomind",
    "split": "val",
    "number": 8,
    "title": "Opening a bin lid",
    "focus": "Lid geometry and contact",
    "directory": "assets/comparisons/robomind/val/08",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-11",
    "dataset": "robomind",
    "split": "val",
    "number": 11,
    "title": "Moving a green pepper onto a plate",
    "focus": "Object shape",
    "directory": "assets/comparisons/robomind/val/11",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-16",
    "dataset": "robomind",
    "split": "val",
    "number": 16,
    "title": "Taking a mango out of a basket",
    "focus": "Object shape and motion",
    "directory": "assets/comparisons/robomind/val/16",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-17",
    "dataset": "robomind",
    "split": "val",
    "number": 17,
    "title": "Placing a can in a bin",
    "focus": "Object appearance during transport",
    "directory": "assets/comparisons/robomind/val/17",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-18",
    "dataset": "robomind",
    "split": "val",
    "number": 18,
    "title": "Lifting an orange from the table",
    "focus": "Object contour",
    "directory": "assets/comparisons/robomind/val/18",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-val-19",
    "dataset": "robomind",
    "split": "val",
    "number": 19,
    "title": "Grasping a mango",
    "focus": "Gripper contact and object shape",
    "directory": "assets/comparisons/robomind/val/19",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-01",
    "dataset": "robomind",
    "split": "ood",
    "number": 1,
    "title": "Placing a leafy vegetable in a basket",
    "focus": "Object transport without duplication",
    "directory": "assets/comparisons/robomind/ood/01",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-02",
    "dataset": "robomind",
    "split": "ood",
    "number": 2,
    "title": "Lifting a leafy vegetable",
    "focus": "Object attachment to the gripper",
    "directory": "assets/comparisons/robomind/ood/02",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-03",
    "dataset": "robomind",
    "split": "ood",
    "number": 3,
    "title": "Picking up toast",
    "focus": "Bread pickup",
    "directory": "assets/comparisons/robomind/ood/03",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-04",
    "dataset": "robomind",
    "split": "ood",
    "number": 4,
    "title": "Picking up a leafy vegetable",
    "focus": "Object pickup",
    "directory": "assets/comparisons/robomind/ood/04",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-05",
    "dataset": "robomind",
    "split": "ood",
    "number": 5,
    "title": "Placing a leafy vegetable on the table",
    "focus": "Leaf shape and placement",
    "directory": "assets/comparisons/robomind/ood/05",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-09",
    "dataset": "robomind",
    "split": "ood",
    "number": 9,
    "title": "Lifting a green vegetable",
    "focus": "Object pickup",
    "directory": "assets/comparisons/robomind/ood/09",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-11",
    "dataset": "robomind",
    "split": "ood",
    "number": 11,
    "title": "Lowering a leafy vegetable onto the table",
    "focus": "Leaf shape",
    "directory": "assets/comparisons/robomind/ood/11",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-14",
    "dataset": "robomind",
    "split": "ood",
    "number": 14,
    "title": "Lifting toast beside a drawer",
    "focus": "Object attachment",
    "directory": "assets/comparisons/robomind/ood/14",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-18",
    "dataset": "robomind",
    "split": "ood",
    "number": 18,
    "title": "Lowering a pear into a drawer",
    "focus": "Object shape during placement",
    "directory": "assets/comparisons/robomind/ood/18",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "robomind-ood-20",
    "dataset": "robomind",
    "split": "ood",
    "number": 20,
    "title": "Picking up a piece of bread",
    "focus": "Bread shape during pickup",
    "directory": "assets/comparisons/robomind/ood/20",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-01",
    "dataset": "droid",
    "split": "val",
    "number": 1,
    "title": "Stacking colored cups",
    "focus": "Cup transport and stacking",
    "directory": "assets/comparisons/droid/val/01",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-06",
    "dataset": "droid",
    "split": "val",
    "number": 6,
    "title": "Moving cloths onto a tray",
    "focus": "Cloth identity and transport",
    "directory": "assets/comparisons/droid/val/06",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-07",
    "dataset": "droid",
    "split": "val",
    "number": 7,
    "title": "Moving a snack packet into a sink",
    "focus": "Object transport",
    "directory": "assets/comparisons/droid/val/07",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-08",
    "dataset": "droid",
    "split": "val",
    "number": 8,
    "title": "Moving a snack packet onto a shelf",
    "focus": "Object placement",
    "directory": "assets/comparisons/droid/val/08",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-09",
    "dataset": "droid",
    "split": "val",
    "number": 9,
    "title": "Removing a pot lid",
    "focus": "Lid shape and transport",
    "directory": "assets/comparisons/droid/val/09",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-10",
    "dataset": "droid",
    "split": "val",
    "number": 10,
    "title": "Lifting a glass pot lid",
    "focus": "Lid persistence",
    "directory": "assets/comparisons/droid/val/10",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-14",
    "dataset": "droid",
    "split": "val",
    "number": 14,
    "title": "Closing an upper cabinet door",
    "focus": "Door motion",
    "directory": "assets/comparisons/droid/val/14",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-15",
    "dataset": "droid",
    "split": "val",
    "number": 15,
    "title": "Opening a kitchen cabinet",
    "focus": "Door motion and geometry",
    "directory": "assets/comparisons/droid/val/15",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-18",
    "dataset": "droid",
    "split": "val",
    "number": 18,
    "title": "Closing a rice-cooker lid",
    "focus": "Lid shape during closure",
    "directory": "assets/comparisons/droid/val/18",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-val-20",
    "dataset": "droid",
    "split": "val",
    "number": 20,
    "title": "Placing a lid on a pot",
    "focus": "Lid geometry",
    "directory": "assets/comparisons/droid/val/20",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-01",
    "dataset": "droid",
    "split": "ood",
    "number": 1,
    "title": "Bunching a dark cloth",
    "focus": "Cloth motion",
    "directory": "assets/comparisons/droid/ood/01",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-02",
    "dataset": "droid",
    "split": "ood",
    "number": 2,
    "title": "Grasping a jar",
    "focus": "Object persistence without duplication",
    "directory": "assets/comparisons/droid/ood/02",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-04",
    "dataset": "droid",
    "split": "ood",
    "number": 4,
    "title": "Placing a cup in a bowl",
    "focus": "Cup transport and placement",
    "directory": "assets/comparisons/droid/ood/04",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-06",
    "dataset": "droid",
    "split": "ood",
    "number": 6,
    "title": "Stacking a black bowl on a pink bowl",
    "focus": "Bowl orientation at placement",
    "directory": "assets/comparisons/droid/ood/06",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-08",
    "dataset": "droid",
    "split": "ood",
    "number": 8,
    "title": "Stacking a pink bowl on a black bowl",
    "focus": "Bowl geometry",
    "directory": "assets/comparisons/droid/ood/08",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-10",
    "dataset": "droid",
    "split": "ood",
    "number": 10,
    "title": "Placing a toy duck in a pot",
    "focus": "Object shape and placement",
    "directory": "assets/comparisons/droid/ood/10",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-11",
    "dataset": "droid",
    "split": "ood",
    "number": 11,
    "title": "Lifting a yellow cloth corner",
    "focus": "Cloth shape during folding",
    "directory": "assets/comparisons/droid/ood/11",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-13",
    "dataset": "droid",
    "split": "ood",
    "number": 13,
    "title": "Lifting a white cloth",
    "focus": "Cloth shape during transport",
    "directory": "assets/comparisons/droid/ood/13",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-19",
    "dataset": "droid",
    "split": "ood",
    "number": 19,
    "title": "Moving a cup toward a bowl",
    "focus": "Cup attachment to the gripper",
    "directory": "assets/comparisons/droid/ood/19",
    "frames": 17,
    "playback_fps": 8
  },
  {
    "id": "droid-ood-20",
    "dataset": "droid",
    "split": "ood",
    "number": 20,
    "title": "Placing a cup inside a bowl",
    "focus": "Cup geometry and contact",
    "directory": "assets/comparisons/droid/ood/20",
    "frames": 17,
    "playback_fps": 8
  }
];
